[build]
builder = "DOCKERFILE"

[deploy]
preDeployCommand = ["hooky-checker cleanup-snapshots --retain 14 --vacuum"]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
